name: linux-build-qt

on:
  push:
    branches-ignore:
      - release

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install-packages
      run: |
        sudo apt update
        sudo apt install cmake libx11-dev libxft-dev g++-10 qt5-default
    - name: configure-debug
      run: |
        mkdir -p build/debug
        cd build/debug
        cmake ../.. -DRENDERER=QT
    - name: build-debug
      run: |
        cd build/debug
        cmake --build . 
    - name: run-tests-debug
      run: |
        cd build/debug
        tests/tests        
    - name: configure-release
      run: |
        mkdir -p build/release
        cd build/release
        cmake ../.. -DCMAKE_BUILD_TYPE=Release -DRENDERER=QT
    - name: build-release
      run: |
        cd build/release
        cmake --build . 
    - name: run-tests-release
      run: |
        cd build/release
        tests/tests        
