name: linux-build

on:
  push:
    branches-ignore:
      - release

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install-packages
      run: |
        sudo apt update
        sudo apt install cmake libx11-dev libxft-dev libxcursor-dev g++-10
        sudo apt install libgl1-mesa-dev
        sudo pip install -Iv aqtinstall==1.1.6
        sudo python -m aqt install --outputdir /opt/qt 6.1.0 linux desktop
    - name: configure-debug
      run: |
        mkdir -p build/debug
        cd build/debug
        cmake ../..
    - name: build-debug
      run: |
        cd build/debug
        cmake --build . 
    - name: run-tests-debug
      run: |
        cd build/debug
        tests/tests        
    - name: configure-release
      run: |
        mkdir -p build/release
        cd build/release
        cmake ../.. -DCMAKE_BUILD_TYPE=Release
    - name: build-release
      run: |
        cd build/release
        cmake --build . 
    - name: run-tests-release
      run: |
        cd build/release
        tests/tests        
    - name: configure-debug-qt
      run: |
        mkdir -p build-qt/debug
        cd build-qt/debug
        cmake ../.. -DRENDERER=QT -DCMAKE_PREFIX_PATH=/opt/qt/6.1.0/gcc_64
    - name: build-debug-qt
      run: |
        cd build-qt/debug
        cmake --build . 
    - name: run-tests-debug-qt
      run: |
        cd build-qt/debug
        tests/tests        
    - name: configure-release-qt
      run: |
        mkdir -p build-qt/release
        cd build-qt/release
        cmake ../.. -DCMAKE_BUILD_TYPE=Release -DRENDERER=QT -DCMAKE_PREFIX_PATH=/opt/qt/6.1.0/gcc_64
    - name: build-release-qt
      run: |
        cd build-qt/release
        cmake --build . 
    - name: run-tests-release-qt
      run: |
        cd build-qt/release
        tests/tests        
