name: linux-packages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install-packages
      run: |
        sudo apt update
        sudo apt install cmake libx11-dev libxft-dev g++-8
    - name: fetch-subprojects
      run: |
        git clone --verbose https://github.com/terminalpp/tpp-bypass
        git clone --verbose https://github.com/terminalpp/ropen
    - name: configure-release
      run: |
        mkdir -p build/release
        cd build/release
        cmake ../.. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Release
    - name: build-terminalpp-packages
      run: |
        cd build/release
        cmake ../.. -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DPACKAGE_INSTALL=terminalpp
        cmake --build . --target packages
    - name: build-ropen-packages
      run: |
        cd build/release
        cmake ../.. -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DPACKAGE_INSTALL=tpp-ropen
        cmake --build . --target packages
    - name: build-bypass-packages
      run: |
        cd build/release
        cmake ../.. -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DPACKAGE_INSTALL=tpp-bypass
        cmake --build . --target packages
    - uses: actions/upload-artifact@master
      with:
        name: terminalpp.deb
        path: build/release/packages/terminalpp.deb
    - uses: actions/upload-artifact@master
      with:
        name: terminalpp.rpm
        path: build/release/packages/terminalpp.rpm
    - uses: actions/upload-artifact@master
      with:
        name: tpp-bypass.deb
        path: build/release/packages/tpp-bypass.deb
    - uses: actions/upload-artifact@master
      with:
        name: tpp-bypass.rpm
        path: build/release/packages/tpp-bypass.rpm
    - uses: actions/upload-artifact@master
      with:
        name: tpp-ropen.deb
        path: build/release/packages/tpp-ropen.deb
    - uses: actions/upload-artifact@master
      with:
        name: tpp-ropen.rpm
        path: build/release/packages/tpp-ropen.rpm
