name: snapcraft-edge

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-snapcraft
      uses: samuelmeuli/action-snapcraft@v1
    - name: install-packages
      run: |
        sudo apt update
        sudo apt install cmake libx11-dev libxft-dev g++-8
#    - name: fetch-subprojects
#      run: |
#        git clone --verbose https://github.com/terminalpp/website
#        git clone --verbose https://github.com/terminalpp/tpp-bypass
#        git clone --verbose https://github.com/terminalpp/ropen
    - name: build-terminalpp-packages
      run: |
        mkdir -p build/release
        cd build/release
        cmake ../.. -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DPACKAGE_INSTALL=terminalpp
        cmake --build . --target packages
    - uses: actions/upload-artifact@master
      with:
        name: terminalpp.snap
        path: build/release/packages/terminalpp.snap

