# https://github.com/sirredbeard/nim_lang_snap
name: snapcraft-edge

on: []

jobs:
  my-job:
    runs-on: ubuntu-latest
#    container:
#      image: snapcore/snapcraft
    steps:
    - uses: actions/checkout@v1
    - name: install-snapcraft
      run: |
        sudo snap install snapcraft --classic
        sudo chown root:root /
        sudo snap install lxd
        sudo lxd init
    - name: install-packages
      run: |
        sudo apt update
        sudo apt install cmake libx11-dev libxft-dev g++-8
    - name: build-terminalpp-packages
      run: |
        mkdir -p build/release
        cd build/release
        cmake ../.. -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DPACKAGE_INSTALL=terminalpp -DSNAP_EXTRA_ARGS=--use-lxd
        cmake --build . --target packages
    - uses: actions/upload-artifact@master
      with:
        name: terminalpp.snap
        path: build/release/packages/terminalpp.snap

