name: windows-build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: fetch-subprojects
      run: |
        git clone --verbose https://github.com/terminalpp/website
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: build-debug
      run: |
        cd build
        cmake --build . --clean-first --config Debug
    - name: run-tests-debug
      run: |
        cd build\tests\Debug
        .\tests.exe        
    - name: build-release
      run: |
        cd build
        cmake --build . --clean-first --config Release
    - name: run-tests-release
      run: |
        cd build\tests\Release
        .\tests.exe        
    - name: build-terminalpp-packages
      run: |
        cd build
        cmake --build . --target packages
    - uses: actions/upload-artifact@master
      with:
        name: terminalpp.msi
        path: build/packages/terminalpp.msi
